import { getDeskPath, joinPath, writeTextFile } from "@/lib/desk/tauri-fs";
import { getWorkspacePath } from "@/lib/desk/paths";
import { FILE_NAMES } from "@/lib/desk/constants";
import { isTauri } from "@/lib/desk/tauri-fs";
import type { Workspace, Project } from "@/types";

/** HTML comment marking a file as generated — invisible when rendered, still read by agents. */
function generatedHeader(): string {
  return `<!-- Auto-generated by desk.md on ${new Date().toISOString()} — do not edit. Regenerated on workspace/project changes. -->`;
}

/** Sanitize a user-controlled value for use inside a markdown table cell. */
function cell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\s*\n\s*/g, " ").trim();
}

// =============================================================================
// TOP-LEVEL CONTEXT (CLAUDE.md + AGENTS.md + GEMINI.md at the data-folder root)
// =============================================================================

function buildTopLevelContext(workspaces: Workspace[], deskPath: string): string {
  const lines: string[] = [];

  lines.push(generatedHeader());
  lines.push("");
  lines.push("# Desk — AI Agent Context");
  lines.push("");
  lines.push(
    "Desk is a markdown-based work management system. All data lives as `.md` files with YAML frontmatter on the local filesystem — workspaces, projects, tasks, docs, meetings. You're meant to read across it; that's why it's structured this way."
  );
  lines.push("");

  // How this space works (norms, non-imperative)
  lines.push("## How this space works");
  lines.push("");
  lines.push("A few conventions keep this knowledge base coherent and tidy.");
  lines.push("");
  lines.push(
    "**`docs/`** holds notes the user curates — references, drafts, and reference material. Read it freely when you need context. Don't write to it directly; new material flows in via `ai-docs/draft-*.md` and the user promotes it to `docs/` when ready."
  );
  lines.push("");
  lines.push(
    "**`ai-docs/`** is the AI working area. Everything here is AI-written — distilled from conversations, research, or analysis. This is where you capture and organize what you learn."
  );
  lines.push("");
  lines.push(
    "**`tasks/`** and **`meetings/`** are real, committed work items. Treat new ones as something the user decides to add — when you spot a candidate, surface it in chat rather than writing the file yourself."
  );
  lines.push("");
  lines.push(
    "**`.aiignore`** at each workspace root lists files the user has flagged as sensitive (gitignore-style patterns). Honor it. The in-app assistant enforces these exclusions automatically; external agents are asked to do the same."
  );
  lines.push("");

  // Conventions inside ai-docs
  lines.push("## Conventions inside ai-docs");
  lines.push("");
  lines.push("A small vocabulary keeps `ai-docs/` findable as it grows:");
  lines.push("");
  lines.push("- `context.md` — running project brief, kept current as understanding grows");
  lines.push("- `research-{topic}.md` — investigations with sources");
  lines.push("- `notes-{topic}.md` — working notes, append-friendly");
  lines.push("- `draft-{topic}.md` — material destined for `docs/` after review");
  lines.push("- `adr-NNN-{topic}.md` — recorded decisions");
  lines.push("");
  lines.push("Append to an existing note when continuing a thread. New files are for new topics, not new thoughts.");
  lines.push("");

  // Workspaces table
  lines.push("## Workspaces");
  lines.push("");
  if (workspaces.length === 0) {
    lines.push("No workspaces yet.");
  } else {
    lines.push("| Name | ID | Description | Path |");
    lines.push("|------|----|-------------|------|");
    for (const ws of workspaces) {
      const name = ws.isHome ? `${ws.name} (home)` : ws.name;
      const path = `workspaces/${ws.id}/`;
      lines.push(`| ${cell(name)} | ${ws.id} | ${cell(ws.description || "")} | ${path} |`);
    }
  }
  lines.push("");
  lines.push(
    "Each workspace has its own `CLAUDE.md` listing its projects. The workspace marked **(home)** holds the `_capture/` triage inbox and cannot be deleted."
  );
  lines.push("");

  // Finding things — describe what's available, let the agent choose how
  lines.push("## Finding things");
  lines.push("");
  lines.push(
    "Each workspace has a `WORKSPACE_CONTEXT.md` — a one-line-per-file catalog (`path · title · meta · summary`) of every doc, task, and meeting, with a file count at the top. Read it whole for an overview of what a workspace holds and how it's organized; scan it for a topic to jump straight to the right file."
  );
  lines.push("");
  lines.push(
    "The `.md` files are the source of truth. Filenames are date-prefixed slugs and every file carries consistent frontmatter, so they're straightforward to search and read directly when you need full content."
  );
  lines.push("");

  // Directory structure
  lines.push("## Directory Structure");
  lines.push("");
  lines.push("```");
  lines.push(`${deskPath}/`);
  lines.push("├── CLAUDE.md / AGENTS.md / GEMINI.md   # this file (3 identical copies)");
  lines.push("├── .desk/                              # app metadata — do not edit");
  lines.push("└── workspaces/");
  lines.push("    └── {workspaceId}/                  # one folder per workspace");
  lines.push("        ├── workspace.md               # metadata");
  lines.push("        ├── CLAUDE.md / AGENTS.md / GEMINI.md   # workspace anchor (3 copies)");
  lines.push("        ├── WORKSPACE_CONTEXT.md       # AI-generated file catalog");
  lines.push("        ├── .aiignore                  # sensitive paths to skip");
  lines.push("        ├── docs/                      # human-curated");
  lines.push("        ├── ai-docs/                   # AI working area");
  lines.push("        ├── _unassigned/               # items without a project (tasks/docs/meetings)");
  lines.push("        ├── _capture/                  # home workspace only — triage inbox (tasks)");
  lines.push("        └── projects/{projectId}/");
  lines.push("            ├── project.md");
  lines.push("            ├── docs/                  # human-curated");
  lines.push("            ├── ai-docs/               # AI working area");
  lines.push("            ├── tasks/");
  lines.push("            └── meetings/");
  lines.push("```");
  lines.push("");

  // File naming
  lines.push("## File Naming Convention");
  lines.push("");
  lines.push("Tasks, docs, and meetings follow: `YYYY-MM-DD-{slug}.md`");
  lines.push("");
  lines.push("- Date prefix: creation date in ISO format");
  lines.push("- Slug: lowercase, hyphenated title (max 50 chars)");
  lines.push("- The file ID is the filename without `.md`");
  lines.push("");

  // Frontmatter schemas
  lines.push("## Frontmatter Schemas");
  lines.push("");
  lines.push("All files use YAML frontmatter; the markdown body follows `---`.");
  lines.push("");

  lines.push("### Task (`tasks/*.md`)");
  lines.push("```yaml");
  lines.push("---");
  lines.push("title: Setup webhook integration");
  lines.push("status: doing          # backlog | todo | doing | waiting | done");
  lines.push("priority: high         # low | medium | high (optional)");
  lines.push("due: \"2024-06-20\"      # ISO date (optional)");
  lines.push("created: \"2024-06-15\"  # ISO date (required)");
  lines.push("---");
  lines.push("```");
  lines.push("");

  lines.push("### Doc (`docs/*.md` and `ai-docs/*.md`)");
  lines.push("```yaml");
  lines.push("---");
  lines.push("title: Architecture Overview");
  lines.push("created: \"2024-06-15\"");
  lines.push("---");
  lines.push("```");
  lines.push("");

  lines.push("### Meeting (`meetings/*.md`)");
  lines.push("```yaml");
  lines.push("---");
  lines.push("title: Weekly Sync");
  lines.push("date: \"2024-06-15\"     # when meeting occurred (required)");
  lines.push("created: \"2024-06-15\"  # when note was written (required)");
  lines.push("---");
  lines.push("```");
  lines.push("");

  lines.push("### Project (`project.md`)");
  lines.push("```yaml");
  lines.push("---");
  lines.push("name: Website Redesign");
  lines.push("status: active         # active | paused | completed | archived");
  lines.push("description: Complete redesign of the marketing site");
  lines.push("created: \"2024-01-01\"");
  lines.push("---");
  lines.push("```");
  lines.push("");

  lines.push("### Workspace (`workspace.md`)");
  lines.push("```yaml");
  lines.push("---");
  lines.push("name: Acme Corp");
  lines.push("description: Website and backend work");
  lines.push("color: \"#3b82f6\"       # optional");
  lines.push("created: \"2024-01-01\"");
  lines.push("---");
  lines.push("```");
  lines.push("");

  // Creating & editing
  lines.push("## Creating & Editing Items");
  lines.push("");
  lines.push(
    "Every item is a single `.md` file. Write one with frontmatter from the schemas above to add it, change the file to edit it, remove it to delete it — the app picks up filesystem changes automatically."
  );
  lines.push("");
  lines.push(
    "Where to write is covered by **How this space works** above: `ai-docs/` is yours to write freely; new `docs/`, tasks, and meetings are the user's call — draft them in chat or in `ai-docs/draft-*.md` rather than creating those files yourself."
  );
  lines.push("");
  lines.push(
    "To create a project: add a directory under `projects/` with a `project.md`, plus `tasks/`, `docs/`, `ai-docs/`, and `meetings/` subdirectories."
  );
  lines.push("");

  return `${lines.join("\n").trim()}\n`;
}

// =============================================================================
// PER-WORKSPACE CONTEXT (workspaces/{id}/CLAUDE.md + AGENTS.md + GEMINI.md)
// =============================================================================

function buildPerWorkspaceContext(workspace: Workspace, projects: Project[]): string {
  const lines: string[] = [];

  lines.push(generatedHeader());
  lines.push("");
  lines.push(`# ${workspace.name}`);
  lines.push("");
  if (workspace.description) {
    lines.push(workspace.description);
    lines.push("");
  }
  lines.push(`- **Workspace ID**: ${workspace.id}`);
  lines.push(`- **Created**: ${workspace.created}`);
  if (workspace.isHome) {
    lines.push("- **Home workspace** — holds the `_capture/` triage inbox; cannot be deleted.");
  }
  lines.push("");

  lines.push("## Projects");
  lines.push("");
  if (projects.length === 0) {
    lines.push("No projects yet. Items live in `_unassigned/`.");
  } else {
    lines.push("| Name | ID | Status | Description |");
    lines.push("|------|----|--------|-------------|");
    for (const proj of projects) {
      lines.push(
        `| ${cell(proj.name)} | ${proj.id} | ${proj.status} | ${cell(proj.description || "")} |`
      );
    }
  }
  lines.push("");

  lines.push(
    `See \`./${FILE_NAMES.WORKSPACE_CONTEXT_MD}\` for a catalog of all files with summaries. The root \`../../CLAUDE.md\` covers conventions and how this space works.`
  );
  lines.push("");

  return `${lines.join("\n").trim()}\n`;
}

// =============================================================================
// WRITE FUNCTIONS
// =============================================================================

export async function writeTopLevelAgentFiles(workspaces: Workspace[]): Promise<void> {
  if (!isTauri()) return;

  const deskPath = await getDeskPath();
  const content = buildTopLevelContext(workspaces, deskPath);

  await writeTextFile(await joinPath(deskPath, FILE_NAMES.CLAUDE_MD), content);
  await writeTextFile(await joinPath(deskPath, FILE_NAMES.AGENTS_MD), content);
  await writeTextFile(await joinPath(deskPath, FILE_NAMES.GEMINI_MD), content);
}

export async function writePerWorkspaceAgentFiles(
  workspaceId: string,
  workspace: Workspace,
  projects: Project[]
): Promise<void> {
  if (!isTauri()) return;

  const workspacePath = await getWorkspacePath(workspaceId);
  const content = buildPerWorkspaceContext(workspace, projects);

  await writeTextFile(await joinPath(workspacePath, FILE_NAMES.CLAUDE_MD), content);
  await writeTextFile(await joinPath(workspacePath, FILE_NAMES.AGENTS_MD), content);
  await writeTextFile(await joinPath(workspacePath, FILE_NAMES.GEMINI_MD), content);
}
