import { joinPath, writeTextFile } from "@/lib/desk/tauri-fs";
import { getWorkspacePath } from "@/lib/desk/paths";
import type { WorkspaceIndex } from "./types";
import { FILE_NAMES } from "@/lib/desk/constants";
import { useContextStore } from "@/stores/context";

/** Collapse whitespace so a value is safe to place on a single catalog line. */
function oneLine(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function buildWorkspaceContext(index: WorkspaceIndex): string {
  const lines: string[] = [];
  lines.push(`# Workspace Context: ${index.workspaceName}`);
  lines.push("");
  lines.push(
    "<!-- Auto-generated by desk.md — do not edit. Rebuilt on file save and via Settings → Catalog. -->"
  );
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push(`Files indexed: ${index.fileCount}`);

  const previewCount = index.entries.filter((e) => e.isPreview).length;
  if (previewCount > 0) {
    lines.push(
      `Note: ${previewCount} of ${index.entries.length} summaries are raw text previews ` +
        "(built without an AI API key). Add a key in Settings → AI and rebuild for real summaries."
    );
  }
  lines.push("");
  lines.push("Each line below is one file: `path` — title · meta · summary.");
  lines.push("");

  // Group entries: docs first, then AI docs, then tasks, then meetings
  const typeOrder: Record<string, number> = { doc: 0, "ai-doc": 1, task: 2, meeting: 3 };
  const grouped = [...index.entries].sort((a, b) => {
    const orderDiff = (typeOrder[a.type] ?? 9) - (typeOrder[b.type] ?? 9);
    if (orderDiff !== 0) return orderDiff;
    const dateA = a.date ?? a.created ?? '';
    const dateB = b.date ?? b.created ?? '';
    return dateB.localeCompare(dateA);
  });

  let currentType = "";
  for (const entry of grouped) {
    // Section headers
    if (entry.type !== currentType) {
      if (currentType !== "") lines.push("");
      currentType = entry.type;
      const sectionName = entry.type === "ai-doc" ? "AI Docs" : entry.type === "doc" ? "Docs" : entry.type === "task" ? "Tasks" : "Meetings";
      lines.push(`## ${sectionName}`);
      lines.push("");
    }

    const meta: string[] = [];
    if (entry.projectName) meta.push(`project=${entry.projectName}`);
    if (entry.status) meta.push(`status=${entry.status}`);
    if (entry.priority) meta.push(`priority=${entry.priority}`);
    if (entry.date) meta.push(`date=${entry.date}`);

    // One compact line per file: `path` — title · meta · summary
    const parts = [oneLine(entry.title)];
    if (meta.length > 0) parts.push(meta.join(", "));
    parts.push(oneLine(entry.summary) || "(no summary)");
    lines.push(`- \`${entry.path}\` — ${parts.join(" · ")}`);
  }

  return `${lines.join("\n").trim()}\n`;
}

export async function writeWorkspaceContextArtifact(index: WorkspaceIndex): Promise<void> {
  if (!useContextStore.getState().generateAgentFiles) return;

  const workspacePath = await getWorkspacePath(index.workspaceId);
  const filePath = await joinPath(workspacePath, FILE_NAMES.WORKSPACE_CONTEXT_MD);
  await writeTextFile(filePath, buildWorkspaceContext(index));
}
