import { getDeskPath, joinPath } from "@desk/core";
import { getStorage } from "@desk/core";
import { getWorkspacePath } from "@desk/core";
import { FILE_NAMES, DESK_SPACE_NORMS } from "@desk/core";
import { isLocalDisk } from "@/lib/connection";
import { useAgentSettingsStore } from "@/stores/agent-settings";
import { useAgentInstructionsStore } from "@/stores/agent-instructions";
import type { Workspace, Project } from "@desk/core/types";

// Generated agent markdown (CLAUDE.md/AGENTS.md/GEMINI.md/WORKSPACE_CONTEXT.md) is a
// LOCAL-mode feature: it teaches a local CLI agent the on-disk tree. In hosted mode the
// data lives on the server and MCP is the external-agent interface, so we don't write
// these into the server tree. They only belong on a real local disk — exactly isLocalDisk().
function skipAgentFileWrite(): boolean {
  return !isLocalDisk();
}

/** HTML comment marking a file as generated — invisible when rendered, still read by agents. */
function generatedHeader(): string {
  return `<!-- Auto-generated by desk.md on ${new Date().toISOString()}. Do not edit by hand. Marker-block content comes from Settings → Agents; everything else is overwritten on regen. -->`;
}

/** Sanitize a user-controlled value for use inside a markdown table cell. */
function cell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\s*\n\s*/g, " ").trim();
}

// Marker block is always emitted (with placeholder when empty) so the parse target is stable.
function userInstructionsBlock(value: string, placeholder: string): string {
  const trimmed = value.trim();
  const body = trimmed.length > 0 ? trimmed : `_${placeholder}_`;
  return [
    "<!-- desk:user-instructions:start -->",
    body,
    "<!-- desk:user-instructions:end -->",
  ].join("\n");
}

// =============================================================================
// TOP-LEVEL CONTEXT (CLAUDE.md + AGENTS.md + GEMINI.md at the data-folder root)
// =============================================================================

function buildTopLevelContext(workspaces: Workspace[], deskPath: string): string {
  const lines: string[] = [];

  lines.push(generatedHeader());
  lines.push("");
  lines.push("# Desk: AI Agent Context");
  lines.push("");
  lines.push(
    "Desk is a markdown-based work management system. All data lives as `.md` files with YAML frontmatter on the local filesystem: workspaces, projects, tasks, docs, meetings. You're meant to read across it; that's why it's structured this way."
  );
  lines.push("");

  // How this space works — the shared norms. Same constant the MCP server ships as
  // `instructions`, so a local agent and a hosted one read the identical conventions.
  lines.push(DESK_SPACE_NORMS);
  lines.push("");

  // Your instructions — user-editable block
  const globalInstructions = useAgentInstructionsStore.getState().global;
  lines.push("## Your instructions");
  lines.push("");
  lines.push(
    userInstructionsBlock(
      globalInstructions,
      "No custom instructions configured (Settings → Agents)."
    )
  );
  lines.push("");

  // Workspaces table
  lines.push("## Workspaces");
  lines.push("");
  if (workspaces.length === 0) {
    lines.push("No workspaces yet.");
  } else {
    lines.push("| Name | ID | Description | Path |");
    lines.push("|------|----|-------------|------|");
    for (const ws of workspaces) {
      const name = ws.isHome ? `${ws.name} (home)` : ws.name;
      const path = `workspaces/${ws.id}/`;
      lines.push(`| ${cell(name)} | ${ws.id} | ${cell(ws.description || "")} | ${path} |`);
    }
  }
  lines.push("");
  lines.push(
    "Each workspace has its own anchor file listing its projects. The workspace marked **(home)** holds the `_capture/` triage inbox and cannot be deleted."
  );
  lines.push("");

  // Finding things — the catalog only; the lifecycle conventions live in the norms above.
  lines.push("## Finding things");
  lines.push("");
  lines.push(
    "Each workspace has a **`WORKSPACE_CONTEXT.md`**: a one-line-per-file catalog (`path · title · meta · summary`) of every file, with a file count at the top. It is the index, not the story — scan it for a topic to jump straight to the right file. The `.md` files themselves are the source of truth and are straightforward to search and read directly."
  );
  lines.push("");

  // Directory structure
  lines.push("## Directory Structure");
  lines.push("");
  lines.push("```");
  lines.push(`${deskPath}/`);
  lines.push("├── CLAUDE.md / AGENTS.md / GEMINI.md   # this file (identical copies; emit toggles in Settings → Agents)");
  lines.push("├── .desk/                              # app metadata (do not edit)");
  lines.push("└── workspaces/");
  lines.push("    └── {workspaceId}/                  # one folder per workspace");
  lines.push("        ├── workspace.md               # metadata");
  lines.push("        ├── CLAUDE.md / AGENTS.md / GEMINI.md   # workspace anchor (identical copies)");
  lines.push("        ├── WORKSPACE_CONTEXT.md       # AI-generated file catalog");
  lines.push("        ├── .aiignore                  # sensitive paths to skip");
  lines.push("        ├── context/                   # the map: evergreen, maintained");
  lines.push("        ├── docs/                      # records: dated, accumulate, never rewritten");
  lines.push("        ├── _unassigned/               # items without a project (tasks/docs/meetings)");
  lines.push("        ├── _capture/                  # home workspace only (triage inbox for tasks)");
  lines.push("        └── projects/{projectId}/");
  lines.push("            ├── project.md");
  lines.push("            ├── context/               # the map (per project): *-brief.md (user's), *-state.md (app-maintained)");
  lines.push("            ├── docs/                  # records");
  lines.push("            ├── tasks/");
  lines.push("            └── meetings/");
  lines.push("```");
  lines.push("");

  // File naming
  lines.push("## File Naming Convention");
  lines.push("");
  lines.push("Tasks, docs, and meetings follow: `YYYY-MM-DD-{slug}.md`");
  lines.push("");
  lines.push("- Date prefix: creation date in ISO format");
  lines.push("- Slug: lowercase, hyphenated title (max 50 chars)");
  lines.push("- The file ID is the filename without `.md`");
  lines.push("");

  // Frontmatter schemas
  lines.push("## Frontmatter Schemas");
  lines.push("");
  lines.push("All files use YAML frontmatter; the markdown body follows `---`.");
  lines.push("");

  lines.push("### Task (`tasks/*.md`)");
  lines.push("```yaml");
  lines.push("---");
  lines.push("title: Setup webhook integration");
  lines.push("status: doing          # backlog | todo | doing | waiting | done");
  lines.push("priority: high         # low | medium | high (optional)");
  lines.push("due: \"2024-06-20\"      # ISO date (optional)");
  lines.push("created: \"2024-06-15\"  # ISO date (required)");
  lines.push("---");
  lines.push("```");
  lines.push("");

  lines.push("### Doc (`docs/*.md` and `context/*.md`)");
  lines.push("```yaml");
  lines.push("---");
  lines.push("title: Architecture Overview");
  lines.push("created: \"2024-06-15\"");
  lines.push("author: ai        # only when you wrote it; omit entirely for the user's own files");
  lines.push("---");
  lines.push("```");
  lines.push("");

  lines.push("### Meeting (`meetings/*.md`)");
  lines.push("```yaml");
  lines.push("---");
  lines.push("title: Weekly Sync");
  lines.push("date: \"2024-06-15\"     # when meeting occurred (required)");
  lines.push("created: \"2024-06-15\"  # when note was written (required)");
  lines.push("---");
  lines.push("```");
  lines.push("");

  lines.push("### Project (`project.md`)");
  lines.push("```yaml");
  lines.push("---");
  lines.push("name: Website Redesign");
  lines.push("status: active         # active | paused | completed | archived");
  lines.push("description: Complete redesign of the marketing site");
  lines.push("created: \"2024-01-01\"");
  lines.push("---");
  lines.push("```");
  lines.push("");

  lines.push("### Workspace (`workspace.md`)");
  lines.push("```yaml");
  lines.push("---");
  lines.push("name: Acme Corp");
  lines.push("description: Website and backend work");
  lines.push("color: \"#3b82f6\"       # optional");
  lines.push("created: \"2024-01-01\"");
  lines.push("---");
  lines.push("```");
  lines.push("");

  // Creating & editing
  lines.push("## Creating & Editing Items");
  lines.push("");
  lines.push(
    "Every item is a single `.md` file. Write one with frontmatter from the schemas above to add it, change the file to edit it, remove it to delete it. The app picks up filesystem changes automatically. Where to write is covered by **How this space works** above."
  );
  lines.push("");
  lines.push(
    "To create a project: add a directory under `projects/` with a `project.md`, plus `context/`, `tasks/`, `docs/`, and `meetings/` subdirectories."
  );
  lines.push("");

  return `${lines.join("\n").trim()}\n`;
}

// =============================================================================
// PER-WORKSPACE CONTEXT (workspaces/{id}/CLAUDE.md + AGENTS.md + GEMINI.md)
// =============================================================================

function buildPerWorkspaceContext(workspace: Workspace, projects: Project[]): string {
  const lines: string[] = [];

  lines.push(generatedHeader());
  lines.push("");
  lines.push(`# ${workspace.name}`);
  lines.push("");
  if (workspace.description) {
    lines.push(workspace.description);
    lines.push("");
  }
  lines.push(`- **Workspace ID**: ${workspace.id}`);
  lines.push(`- **Created**: ${workspace.created}`);
  if (workspace.isHome) {
    lines.push("- **Home workspace**: holds the `_capture/` triage inbox; cannot be deleted.");
  }
  lines.push("");

  // Workspace-specific instructions — user-editable block
  const workspaceInstructions =
    useAgentInstructionsStore.getState().perWorkspace[workspace.id] ?? "";
  lines.push("## Workspace-specific instructions");
  lines.push("");
  lines.push(
    userInstructionsBlock(
      workspaceInstructions,
      "No workspace-specific instructions configured (Settings → Agents)."
    )
  );
  lines.push("");

  lines.push("## Projects");
  lines.push("");
  if (projects.length === 0) {
    lines.push("No projects yet. Items live in `_unassigned/`.");
  } else {
    lines.push("| Name | ID | Status | Description |");
    lines.push("|------|----|--------|-------------|");
    for (const proj of projects) {
      lines.push(
        `| ${cell(proj.name)} | ${proj.id} | ${proj.status} | ${cell(proj.description || "")} |`
      );
    }
  }
  lines.push("");

  lines.push(
    `See \`./${FILE_NAMES.WORKSPACE_CONTEXT_MD}\` for a catalog of all files with summaries. The root anchor file covers conventions and how this space works.`
  );
  lines.push("");

  return `${lines.join("\n").trim()}\n`;
}

// =============================================================================
// WRITE FUNCTIONS
// =============================================================================

/** Map of agent filenames to their corresponding emit-toggle flag in the context store. */
function enabledAgentFilenames(): string[] {
  const s = useAgentSettingsStore.getState();
  const out: string[] = [];
  if (s.emitClaudeMd) out.push(FILE_NAMES.CLAUDE_MD);
  if (s.emitAgentsMd) out.push(FILE_NAMES.AGENTS_MD);
  if (s.emitGeminiMd) out.push(FILE_NAMES.GEMINI_MD);
  return out;
}

/** All three filenames whose emit-toggle is OFF — these get deleted on write. */
function disabledAgentFilenames(): string[] {
  const s = useAgentSettingsStore.getState();
  const out: string[] = [];
  if (!s.emitClaudeMd) out.push(FILE_NAMES.CLAUDE_MD);
  if (!s.emitAgentsMd) out.push(FILE_NAMES.AGENTS_MD);
  if (!s.emitGeminiMd) out.push(FILE_NAMES.GEMINI_MD);
  return out;
}

/** Remove a file if it's present; a missing file is not an error. */
async function removeIfExists(path: string): Promise<void> {
  if (await getStorage().exists(path)) await getStorage().removeFile(path);
}

export async function writeTopLevelAgentFiles(workspaces: Workspace[]): Promise<void> {
  if (skipAgentFileWrite()) return;

  const deskPath = await getDeskPath();
  const enabled = enabledAgentFilenames();
  const disabled = disabledAgentFilenames();

  if (enabled.length > 0) {
    const content = buildTopLevelContext(workspaces, deskPath);
    for (const name of enabled) {
      await getStorage().writeTextFile(await joinPath(deskPath, name), content);
    }
  }

  // Sweep any files for toggles that are off — keeps disk in sync with settings.
  for (const name of disabled) {
    await removeIfExists(await joinPath(deskPath, name));
  }
}

export async function writePerWorkspaceAgentFiles(
  workspaceId: string,
  workspace: Workspace,
  projects: Project[]
): Promise<void> {
  if (skipAgentFileWrite()) return;

  const workspacePath = await getWorkspacePath(workspaceId);
  const enabled = enabledAgentFilenames();
  const disabled = disabledAgentFilenames();

  if (enabled.length > 0) {
    const content = buildPerWorkspaceContext(workspace, projects);
    for (const name of enabled) {
      await getStorage().writeTextFile(await joinPath(workspacePath, name), content);
    }
  }

  for (const name of disabled) {
    await removeIfExists(await joinPath(workspacePath, name));
  }
}

// Delete every generated agent file from the data folder; used when the catalog is cleared.
export async function deleteGeneratedAgentFiles(workspaces: Workspace[]): Promise<void> {
  if (skipAgentFileWrite()) return;

  const deskPath = await getDeskPath();
  for (const name of [FILE_NAMES.CLAUDE_MD, FILE_NAMES.AGENTS_MD, FILE_NAMES.GEMINI_MD]) {
    await removeIfExists(await joinPath(deskPath, name));
  }

  for (const ws of workspaces) {
    const workspacePath = await getWorkspacePath(ws.id);
    for (const name of [
      FILE_NAMES.CLAUDE_MD,
      FILE_NAMES.AGENTS_MD,
      FILE_NAMES.GEMINI_MD,
      FILE_NAMES.WORKSPACE_CONTEXT_MD,
    ]) {
      await removeIfExists(await joinPath(workspacePath, name));
    }
  }
}
