import { joinPath } from "@desk/core";
import { getStorage } from "@desk/core";
import { getWorkspacePath } from "@desk/core";
import type { WorkspaceIndex } from "@desk/core";
import { FILE_NAMES } from "@desk/core";
import { isLocalDisk } from "@/lib/connection";
import { anyAgentFileEnabled } from "@/stores/agent-settings";

/** Collapse whitespace so a value is safe to place on a single catalog line. */
function oneLine(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function buildWorkspaceContext(index: WorkspaceIndex): string {
  const lines: string[] = [];
  lines.push(`# Workspace Context: ${index.workspaceName}`);
  lines.push("");
  lines.push(
    "<!-- Auto-generated by desk.md. Do not edit. Rebuilt on file save and via Settings → Catalog. -->"
  );
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push(`Files indexed: ${index.fileCount}`);

  const summarized = index.entries.filter((e) => e.summary).length;
  if (summarized < index.entries.length) {
    lines.push(
      `Note: ${summarized} of ${index.entries.length} files have an AI summary. ` +
        "Add a key in Settings → AI and rebuild to summarize the rest."
    );
  }
  lines.push("");
  lines.push("Each line below is one file: `path` · title · meta · summary.");
  lines.push("");
  lines.push(
    "**Context** is the maintained map — read it first to orient yourself. " +
      "**Docs**, **Tasks**, and **Meetings** are dated records that accumulate."
  );
  lines.push("");

  // Context first — it is the orientation layer — then the records.
  const typeOrder: Record<string, number> = { context: 0, doc: 1, task: 2, meeting: 3 };
  const grouped = [...index.entries].sort((a, b) => {
    const orderDiff = (typeOrder[a.type] ?? 9) - (typeOrder[b.type] ?? 9);
    if (orderDiff !== 0) return orderDiff;
    const dateA = a.date ?? a.created ?? '';
    const dateB = b.date ?? b.created ?? '';
    return dateB.localeCompare(dateA);
  });

  let currentType = "";
  for (const entry of grouped) {
    // Section headers
    if (entry.type !== currentType) {
      if (currentType !== "") lines.push("");
      currentType = entry.type;
      const sectionName = entry.type === "context" ? "Context" : entry.type === "doc" ? "Docs" : entry.type === "task" ? "Tasks" : "Meetings";
      lines.push(`## ${sectionName}`);
      lines.push("");
    }

    const meta: string[] = [];
    if (entry.projectName) meta.push(`project=${entry.projectName}`);
    if (entry.status) meta.push(`status=${entry.status}`);
    if (entry.priority) meta.push(`priority=${entry.priority}`);
    if (entry.date) meta.push(`date=${entry.date}`);
    if (entry.author) meta.push(`author=${entry.author}`);

    // One compact line per file: `path` · title · meta · summary
    const parts = [oneLine(entry.title)];
    if (meta.length > 0) parts.push(meta.join(", "));
    parts.push(entry.summary ? oneLine(entry.summary) : "(no summary)");
    lines.push(`- \`${entry.path}\` · ${parts.join(" · ")}`);
  }

  return `${lines.join("\n").trim()}\n`;
}

export async function writeWorkspaceContextArtifact(index: WorkspaceIndex): Promise<void> {
  // WORKSPACE_CONTEXT.md is a local-mode artifact (paired with the agent files that
  // point at it); in hosted mode MCP is the external-agent interface, so we don't
  // write it into the server tree. It only belongs on a real local disk — isLocalDisk().
  if (!isLocalDisk()) return;
  // The catalog only makes sense alongside the agent files that point at it.
  if (!anyAgentFileEnabled()) return;

  const workspacePath = await getWorkspacePath(index.workspaceId);
  const filePath = await joinPath(workspacePath, FILE_NAMES.WORKSPACE_CONTEXT_MD);
  await getStorage().writeTextFile(filePath, buildWorkspaceContext(index));
}
